services:
  - type: web
    name: omniroute
    env: python
    buildCommand: "./build.sh"
    startCommand: "daphne -b 0.0.0.0 -p $PORT omniroute.asgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com,localhost,127.0.0.1"
      - key: DATABASE_URL
        fromDatabase:
          name: omniroute-db
          property: connectionString

databases:
  - name: omniroute-db
    databaseName: omniroute
    user: omniroute
