services:
  - type: web
    name: omniroute-backend
    env: python
    rootDir: backend
    buildCommand: "./build.sh"
    startCommand: "daphne -b 0.0.0.0 -p $PORT config.asgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com,localhost,127.0.0.1"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://*.onrender.com"

  - type: web
    name: omniroute-frontend
    env: static
    rootDir: frontend
    buildCommand: "npm run build"
    staticPublishPath: dist
