# Generated by Django 4.2.30 on 2026-07-24 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkippedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('skipped_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skips_received', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skips_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'skipped_users',
                'indexes': [models.Index(fields=['user', 'skipped_user'], name='skipped_use_user_id_a36101_idx')],
            },
        ),
        migrations.CreateModel(
            name='MatchQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferences', models.JSONField(blank=True, default=dict)),
                ('match_mode', models.CharField(default='random', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('last_searched_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='active_queue', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'match_queue',
                'indexes': [models.Index(fields=['is_active', 'entered_at'], name='match_queue_is_acti_e4fe45_idx')],
            },
        ),
        migrations.CreateModel(
            name='MatchHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('match_score', models.FloatField(default=0.0)),
                ('matched_at', models.DateTimeField(auto_now_add=True)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_user2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'match_history',
                'indexes': [models.Index(fields=['user1', 'user2'], name='match_histo_user1_i_73c503_idx'), models.Index(fields=['matched_at'], name='match_histo_matched_c2741f_idx')],
            },
        ),
    ]
