# Generated by Django 4.2.30 on 2026-08-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='room_type',
            field=models.CharField(choices=[('random', 'Random Chat'), ('friend', 'Friend Chat')], default='random', max_length=20),
        ),
    ]
