# Generated by Django 4.2.30 on 2026-07-23 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired'), ('matched', 'Matched')], default='pending', max_length=20)),
                ('sender_preferences', models.JSONField(blank=True, default=dict)),
                ('receiver_preferences', models.JSONField(blank=True, default=dict)),
                ('match_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_requests_received', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_requests_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sender', 'status'], name='matching_ma_sender__ceca38_idx'), models.Index(fields=['receiver', 'status'], name='matching_ma_receive_1e68a1_idx'), models.Index(fields=['created_at'], name='matching_ma_created_1a37c4_idx')],
            },
        ),
        migrations.CreateModel(
            name='MatchQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferences', models.JSONField(blank=True, default=dict)),
                ('match_mode', models.CharField(default='random', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('last_searched_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='match_queue', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['is_active', 'entered_at'], name='matching_ma_is_acti_33ead6_idx')],
            },
        ),
        migrations.CreateModel(
            name='MatchHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('match_score', models.FloatField(default=0.0)),
                ('matched_at', models.DateTimeField(auto_now_add=True)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_history_1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_history_2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-matched_at'],
                'indexes': [models.Index(fields=['user1', 'user2'], name='matching_ma_user1_i_cb3fae_idx'), models.Index(fields=['matched_at'], name='matching_ma_matched_d9c6ba_idx')],
            },
        ),
    ]
